### ISSUE TITLE
Very cool - iOS support planned?

### ISSUE THREAD

**Issue by Noitidart** [Ibrahim-GHub/react-native-android-circular-reveal#1]
Thank you Ibrahim for such an awesome lib, do you have support for iOS planned? I know material design is not usually seen on iOS, but I feel this effect can have great use outside of material.

**Comment by ibrahimahmed-io** [comment]
Unfortunately i have no plans on creating iOS support, The package is just a wrapper for [Circular Reveal](https://github.com/ozodrukh/CircularReveal)
